GET http://127.0.0.1:8000/api/v1/titles/
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY3MTQwNTUzLCJqdGkiOiI3YzU4NTBjNGY2ZTU0M2NiYjZlM2U3ODY1MGNhMTYxYyIsInVzZXJfaWQiOjF9.-fdZ2pqbgAoB4A8kmLGlov0jpJS0zaE8JFwEDDJ90dU
#Authorization: Token 10b64010ba9126c2ff47ca2e60b4ebf881ae59bcAuthorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY2NjExNjA5LCJqdGkiOiJkZjE0ZTQ2ODRiYjc0NjE0YmQ1NWM1ZDZkNmQ5YjRkZCIsInVzZXJfaWQiOjJ9.NZF5f2u_FMLH2OO6mLH7FyYYr_Uj9nlZ7oqUbtF5m98
###

###

GET http://127.0.0.1:8000/api/v1/posts/1/
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY3MTQwNTUzLCJqdGkiOiI3YzU4NTBjNGY2ZTU0M2NiYjZlM2U3ODY1MGNhMTYxYyIsInVzZXJfaWQiOjF9.-fdZ2pqbgAoB4A8kmLGlov0jpJS0zaE8JFwEDDJ90dU

###

###

POST http://127.0.0.1:8000/api/v1/titles/1/
Content-Type: application/json
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY3MjIwNTkyLCJqdGkiOiI5ZmU1MTQ2ZTNkZTU0MzQ4YjI3ZTg1ODA2MWExODU1MSIsInVzZXJfaWQiOjF9.fKlqxLPneFReLN6E7cv8DobCXuScd8S_Opf2y7EakMk

{
    "name": "Побег из Шоушенка 2",
    "year": 1994,
    "description": "Шоушенк",
    "genre": "triller",
    "category": "movie"
} 
###

###

POST http://127.0.0.1:8000/api/v1/genres/
Content-Type: application/json
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY3MjIwNTkyLCJqdGkiOiI5ZmU1MTQ2ZTNkZTU0MzQ4YjI3ZTg1ODA2MWExODU1MSIsInVzZXJfaWQiOjF9.fKlqxLPneFReLN6E7cv8DobCXuScd8S_Opf2y7EakMk

{
    "name": "Триллер",
    "slug": "triller"
} 
###

###

POST http://127.0.0.1:8000/api/v1/categories/
Content-Type: application/json
#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY3MjIwNTkyLCJqdGkiOiI5ZmU1MTQ2ZTNkZTU0MzQ4YjI3ZTg1ODA2MWExODU1MSIsInVzZXJfaWQiOjF9.fKlqxLPneFReLN6E7cv8DobCXuScd8S_Opf2y7EakMk

{
    "name": "Фильм",
    "slug": "movie"
} 
###

###


POST http://127.0.0.1:8000/api/v1/jwt/create/
Content-Type: application/json
#Authorization: Token dd1a674136947a403057caec4adb4ba04d340943
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY2NjYwNzU3NSwianRpIjoiZDQ1NzUxZDlkOTUwNDg2YTlkZmVmZGJlYzUzMDEzNmQiLCJ1c2VyX2lkIjoyfQ.JMGu6eXzNkqy3QxUmPXFcrlem6ZTv5DrDWGBqqHBur8Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY2NjExNjA5LCJqdGkiOiJkZjE0ZTQ2ODRiYjc0NjE0YmQ1NWM1ZDZkNmQ5YjRkZCIsInVzZXJfaWQiOjJ9.NZF5f2u_FMLH2OO6mLH7FyYYr_Uj9nlZ7oqUbtF5m98

{
    "username": "admin",
    "password": "admin"
} 
###

###

POST http://127.0.0.1:8000/api/v1/api-token-auth/
Content-Type: application/json
#Authorization: Token 92d74761dd0dab01eb441aaff8dff2c22cd89ee4
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY2NjYwNzU3NSwianRpIjoiZDQ1NzUxZDlkOTUwNDg2YTlkZmVmZGJlYzUzMDEzNmQiLCJ1c2VyX2lkIjoyfQ.JMGu6eXzNkqy3QxUmPXFcrlem6ZTv5DrDWGBqqHBur8#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY2NjExNjA5LCJqdGkiOiJkZjE0ZTQ2ODRiYjc0NjE0YmQ1NWM1ZDZkNmQ5YjRkZCIsInVzZXJfaWQiOjJ9.NZF5f2u_FMLH2OO6mLH7FyYYr_Uj9nlZ7oqUbtF5m98

{
    "username": "Mike",
    "password": "123Leo123"
} 
###

###

POST http://127.0.0.1:8000/api/v1/api-token-auth/
Content-Type: application/json
#Authorization: Token 3eb4a29d2d0b0941a0f72798374cb641c693e129
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY2NjYwNzU3NSwianRpIjoiZDQ1NzUxZDlkOTUwNDg2YTlkZmVmZGJlYzUzMDEzNmQiLCJ1c2VyX2lkIjoyfQ.JMGu6eXzNkqy3QxUmPXFcrlem6ZTv5DrDWGBqqHBur8#Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjY2NjExNjA5LCJqdGkiOiJkZjE0ZTQ2ODRiYjc0NjE0YmQ1NWM1ZDZkNmQ5YjRkZCIsInVzZXJfaWQiOjJ9.NZF5f2u_FMLH2OO6mLH7FyYYr_Uj9nlZ7oqUbtF5m98

{
    "username": "Mike2",
    "password": "qwerty123"
} 
###

###