### Получить код на почту
POST http://127.0.0.1:8000/api/v1/auth/signup/
Content-Type: application/json

{
    "username": "user2",
    "email": "user2@admin.admin"
}

### Получить токен
POST http://localhost:8000/api/v1/auth/token/
Content-Type: application/json

{
    "username": "user2",
    "token": "662-fad515350fecce408908"
}

###
DELETE  http://localhost:8000/api/v1/users/me/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNDU1NzE1LCJpYXQiOjE2Njg4NjM3MTUsImp0aSI6IjUxYWM1Yjk4NmU4MDRhNjA5ZWQ1ODE5OTgwOTBiN2I3IiwidXNlcl9pZCI6MX0.Dg7oBdaXxaS8MFDfZsJmuM6xqIy6bm-2sroziI71IWc


### Получить всех пользователей
GET http://localhost:8000/api/v1/users/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNTIzODExLCJpYXQiOjE2Njg5MzE4MTEsImp0aSI6ImUzYWQ2OTQzYzU2YTQ1ODM4YWU4YzA5M2Y3MmM0ZmVmIiwidXNlcl9pZCI6Mn0.1JtO4TwGmzVVWcr6yW6uCk5SUbxYL8u7aVO12X3age8




### Создать пользователя (только Админ)
POST http://localhost:8000/api/v1/users/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNDU1NzE1LCJpYXQiOjE2Njg4NjM3MTUsImp0aSI6IjUxYWM1Yjk4NmU4MDRhNjA5ZWQ1ODE5OTgwOTBiN2I3IiwidXNlcl9pZCI6MX0.Dg7oBdaXxaS8MFDfZsJmuM6xqIy6bm-2sroziI71IWc

{
    "username": "user7",
    "email": "user2@user.user"
}


### Получить пользователя по имени (только Админ)
GET http://localhost:8000/api/v1/users/user1/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNDU1NzE1LCJpYXQiOjE2Njg4NjM3MTUsImp0aSI6IjUxYWM1Yjk4NmU4MDRhNjA5ZWQ1ODE5OTgwOTBiN2I3IiwidXNlcl9pZCI6MX0.Dg7oBdaXxaS8MFDfZsJmuM6xqIy6bm-2sroziI71IWc

### Изменить пользователя по имени (только Админ)
PATCH http://localhost:8000/api/v1/users/user1/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNDU1NzE1LCJpYXQiOjE2Njg4NjM3MTUsImp0aSI6IjUxYWM1Yjk4NmU4MDRhNjA5ZWQ1ODE5OTgwOTBiN2I3IiwidXNlcl9pZCI6MX0.Dg7oBdaXxaS8MFDfZsJmuM6xqIy6bm-2sroziI71IWc

{
    "username": "user1",
    "role": "admin"
}



### Получить себя - user2
GET http://localhost:8000/api/v1/users/me/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNTI1ODA5LCJpYXQiOjE2Njg5MzM4MDksImp0aSI6ImU1NWE4ZmI2Yzg0ZjQ4ZGFhYmNjODlkOThmOTE4ZGQyIiwidXNlcl9pZCI6Nn0.AsOs9ioll-XcuMNG9272wnizVG4tcP86FkLgbu_f_SA

### Patch себя - user2
PATCH http://localhost:8000/api/v1/users/me/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNTI1ODA5LCJpYXQiOjE2Njg5MzM4MDksImp0aSI6ImU1NWE4ZmI2Yzg0ZjQ4ZGFhYmNjODlkOThmOTE4ZGQyIiwidXNlcl9pZCI6Nn0.AsOs9ioll-XcuMNG9272wnizVG4tcP86FkLgbu_f_SA

{
    "role": "admin",
    "bio": "My bio"
}
