### Получить код на почту
POST http://127.0.0.1:8000/api/v1/auth/signup/
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@admin.admin"
}

### Получить токен
POST http://localhost:8000/api/v1/auth/token/
Content-Type: application/json

{
    "username": "admin",
    "confirmation_code": "663-8b4031cbdf537c9dc57b"
}

###
DELETE  http://localhost:8000/api/v1/users/me/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNzMzNTQwLCJqdGkiOiI1OTI3YzhhZGY5ZTM0M2UyYmQ4YjM3Y2M0Yzk5MzkyMiIsInVzZXJfaWQiOjJ9.CEYPqJEO0TCORz5_0_OcJlu96b2HOHupS7WPw9h4ncM


### Получить всех пользователей
GET http://localhost:8000/api/v1/users/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNzMzNTQwLCJqdGkiOiI1OTI3YzhhZGY5ZTM0M2UyYmQ4YjM3Y2M0Yzk5MzkyMiIsInVzZXJfaWQiOjJ9.CEYPqJEO0TCORz5_0_OcJlu96b2HOHupS7WPw9h4ncM




### Создать пользователя (только Админ)
POST http://localhost:8000/api/v1/users/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNzMzNTQwLCJqdGkiOiI1OTI3YzhhZGY5ZTM0M2UyYmQ4YjM3Y2M0Yzk5MzkyMiIsInVzZXJfaWQiOjJ9.CEYPqJEO0TCORz5_0_OcJlu96b2HOHupS7WPw9h4ncM

{
    "username": "user2",
    "email": "user2@user.user"
}


### Получить пользователя по имени (только Админ)
GET http://localhost:8000/api/v1/users/user1/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNDU1NzE1LCJpYXQiOjE2Njg4NjM3MTUsImp0aSI6IjUxYWM1Yjk4NmU4MDRhNjA5ZWQ1ODE5OTgwOTBiN2I3IiwidXNlcl9pZCI6MX0.Dg7oBdaXxaS8MFDfZsJmuM6xqIy6bm-2sroziI71IWc

### Изменить пользователя по имени (только Админ)
PATCH http://localhost:8000/api/v1/users/user1/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNDU1NzE1LCJpYXQiOjE2Njg4NjM3MTUsImp0aSI6IjUxYWM1Yjk4NmU4MDRhNjA5ZWQ1ODE5OTgwOTBiN2I3IiwidXNlcl9pZCI6MX0.Dg7oBdaXxaS8MFDfZsJmuM6xqIy6bm-2sroziI71IWc

{
    "username": "user1",
    "role": "admin"
}



### Получить себя - user777
GET http://localhost:8000/api/v1/users/me/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNzM2MjQ3LCJqdGkiOiI0YWQ4MmMzNWQ1NjU0NjliOWI2MzIzZmJlNjA3ZjMzYSIsInVzZXJfaWQiOjl9.qS5ZMy1ueHV1iHXPmnHuGB9ZWDI1CxCrSv8juJObl9A

### Patch себя - user777
PATCH http://localhost:8000/api/v1/users/me/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNzM2MjQ3LCJqdGkiOiI0YWQ4MmMzNWQ1NjU0NjliOWI2MzIzZmJlNjA3ZjMzYSIsInVzZXJfaWQiOjl9.qS5ZMy1ueHV1iHXPmnHuGB9ZWDI1CxCrSv8juJObl9A

{
    "username": "User7",
    "role": "admin",
    "bio": "My bio"
}
