# Generated by Django 3.2.16 on 2022-11-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
